---
title: "NYC 311 Calls"
author: "Theresa Diffendal"
date: "1/27/2020"
output: 
  html_document:
      toc: true
      toc_depth: 3
      toc_float: true
    md_document:
      variant: markdown_github
      toc: true
      toc_depth: 3
---

An analysis of New YOrk City's 311 call data from 2010-present. Data found on New York's [open data site](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/data).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

###Libraries

library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(readxl)
library(dplyr)
library(tidyr)
library(data.table)
```


```{r}
##Load the csv, clean names, maniuplate date_time columns 

sskip = 0
nn_max = 0

while(skip < nrow(nyc_calls)) {
  nn_max = nn_max + 500000
  
  nyc_calls <- read_csv("~/Documents/GitHub/homelessness-in-the-us/data/input-data/NYC_311_Service_Requests_from_2010_to_Present.csv", n_max = nn_max, skip = sskip)
  
  sskip = sskip + 500000
}

 nyc_calls %>%
    clean_names() %>% 
    separate(created_date, c("date", "hour", "AM/PM"), " ", remove=FALSE) %>%
    separate("date", c("month", "day", "year")) %>%
    unite("time", "hour":"AM/PM", sep = " ")
  
 
colnames(nyc_calls)

## Working Code

nyc_calls <- read_csv(file="~/Documents/GitHub/homelessness-in-the-us/data/input-data/NYC_311_Service_Requests_from_2010_to_Present.csv", n_max=2)
  #col_types = cols(
  #  "Unique Key" = col_character(),
  #  "Created Date" = col_character()
  #)
  #                    
  #                    ) %>%
  #clean_names() %>%
  #select(1,2) %>%
  #separate(created_date, c("date", "hour", "AM/PM"), " ", remove=FALSE) %>%
  #separate("date", c("month", "day", "year")) %>%
  #unite("time", "hour":"AM/PM", sep = " ")

colnames(nyc_calls)

ccolumns <- list("Unique Key", "Created Date", "Closed Date", "Agency", "Agency Name", "Complaint Type", "Descriptor", "Location Type", "Incident Zip", "Incident Address", "Street Name", "Cross Street 1", "Cross Street 2", "Intersection Street 1", "Intersection Street 2", "Address Type", "City", "Landmark", "Facility Type", "Status", "Due Date", "Resolution Description", "Resolution Action Updated Date", "Community Board", "BBL", "Borough", "X Coordinate (State Plane)", "Y Coordinate (State Plane)", "Open Data Channel Type", "Park Facility Name", "Park Borough", "Vehicle Type", "Taxi Company Borough", "Taxi Pick Up Location", "Bridge Highway Name", "Bridge Highway Direction", "Road Ramp", "Bridge Highway Segment", "Latitude", "Longitude", "Location")

nyc_calls_header <- head(nyc_calls, 0)

rm(nyc_calls)

sskip = 0
nn_max = 0

while(nn_max < 22.4e6) {
  nn_max = nn_max + 50000

  nyc_calls <- read_csv("~/Documents/GitHub/homelessness-in-the-us/data/input-data/NYC_311_Service_Requests_from_2010_to_Present.csv", n_max = nn_max, skip = sskip, col_names = c("Unique Key", "Created Date", "Closed Date", "Agency", "Agency Name", "Complaint Type", "Descriptor", "Location Type", "Incident Zip", "Incident Address", "Street Name", "Cross Street 1", "Cross Street 2", "Intersection Street 1", "Intersection Street 2", "Address Type", "City", "Landmark", "Facility Type", "Status", "Due Date", "Resolution Description", "Resolution Action Updated Date", "Community Board", "BBL", "Borough", "X Coordinate (State Plane)", "Y Coordinate (State Plane)", "Open Data Channel Type", "Park Facility Name", "Park Borough", "Vehicle Type", "Taxi Company Borough", "Taxi Pick Up Location", "Bridge Highway Name", "Bridge Highway Direction", "Road Ramp", "Bridge Highway Segment", "Latitude", "Longitude", "Location")) %>%
  clean_names() %>%
  separate(created_date, c("date", "hour", "AM/PM"), " ", remove=FALSE) %>%
  separate("date", c("month", "day", "year")) %>%
  unite("time", "hour":"AM/PM", sep = " ")
  
  sskip = sskip + 50000
}

summary(nyc_calls_header)


# save as Rds(for faster processing)
#saveRDS(nyc_calls, "~/Documents/GitHub/homelessness-in-the-us/data/input-data/NYC-311-Service-Requests.Rds")
```

```{r}

## Load RDS and clean
nyc_calls <- readRDS("~/Documents/GitHub/homelessness-in-the-us/data/input-data/NYC-311-Service-Requests.Rds",
                     n_max=5000) %>%
  clean_names()

# Make date time column into multiple columns with year, month, day
nyc_calls %>%
  mdy_hms(nyc_calls[,2]) %>%
  mutate(year = year(nyc_calls[,2]),
         month = month(nyc_calls[,2]))
  
#nyc_calls$created_date <- as.Date(mdy_hms(nyc_calls$created_date))


#nyc_calls$created_date <- as.Date(nyc_calls$created_date, "%m/%d/%Y")

```

Observation values pertaining to homelessness:

Agency Name:
* Department of Homeless Services

Complaint type:
* Homeless Street Condition
* Homeless Person Assistance

Descriptor:
* Homeless Issue
  * Under complaint type "Ferry Complaint"

## Analyze each year

### 2010

```{r}

nyc_calls_2010 <- nyc_calls %>%
  filter(year == 2010)

```

### 2011

```{r}

nyc_calls_2011 <- nyc_calls %>%
  filter(year == 2011)

```

### 2012

```{r}

nyc_calls_2012 <- nyc_calls %>%
  filter(year == 2012)

```

### 2013

```{r}

nyc_calls_2013 <- nyc_calls %>%
  filter(year == 2013)

```

### 2014

```{r}

nyc_calls_2014 <- nyc_calls %>%
  filter(year == 2014)

```

### 2015

```{r}

nyc_calls_2015 <- nyc_calls %>%
  filter(year == 2015)

```

### 2016

```{r}

nyc_calls_2016 <- nyc_calls %>%
  filter(year == 2016)

```

### 2017

```{r}

nyc_calls_2017 <- nyc_calls %>%
  filter(year == 2017)

```

### 2018

```{r}

nyc_calls_2018 <- nyc_calls %>%
  filter(year == 2018)

```

### 2019

```{r}

nyc_calls_2019 <- nyc_calls %>%
  filter(year == 2019)

```
