---
title: "Data Sourcing"
author: "Roxanne Ready"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
# Save this file and run the following line from the R console to output both HTML and .md formats:
# rmarkdown::render('data/cleaning.Rmd', output_format = 'all')

# Setup Knitr to display code output by default but suppress messages
knitr::opts_chunk$set(echo = TRUE, paged.print = TRUE, message = FALSE)

# Set the Knitr root directory to the project directory, which is one up from where this document is stored
# (Does not seem to affect links outside code blocks)
knitr::opts_knit$set(root.dir = '../..')
```

## Homelessness

### Zillow

Zillow has a [data portal](https://www.zillow.com/research/data/) with downloads of various datasets available, as well as a simple dictionary. From there, I found the following useful files:

* [Mortgage Affordability, Rent Affordability, Price-to-Income Ratio](input-data/Affordability_Wide_2019Q2_Public.csv) for each quarter from 1979 to 2019 second quarter. May be useful as the latter two are considered strong predictors of homelessness.
* [Zillow-county-to-FIPs crosswalk](input-data/CountyCrossWalk_Zillow.csv)
* [Data request form](https://www.zillow.com/research/contact-us/)

### Inside AirBnB

* [Inside Airbnb](http://insideairbnb.com/get-the-data.html) has compiled listing and review data from AirBnB's website. "The data has been analyzed, cleansed and aggregated where appropriate to faciliate public discussion." Unfortunately, these data are only available for certain cities, can only be downloaded one city at a time, and each city has multiple associated files.
* [Methodology and disclaimers](http://insideairbnb.com/about.html#disclaimers)
* Data request contact person at Inside Airbnb: murray@murraycox.com

### HUD

The U.S. Department of Housing and Urban Development takes Point in Time (PIT) counts of the homeless population yearly for many Continuums of Care (CoCs), and bi-yearly for the remainder.

### Tom Byrne

Tom Byrne has created "a geographic crosswalk between 2017 U.S. Department of Housing and Urban Development (HUD) Continuum of Care (CoC) boundaries and 2017 U.S. Census Bureau geographies (Census tracts and counties)," the GitHub repo for which can be found [here](https://github.com/tomhbyrne/HUD-CoC-Geography-Crosswalk).

## Opioid Epidemic

* CDC WONDER downloadable data: https://wonder.cdc.gov/
* HHS directory of data portals: https://www.hhs.gov/opioids/about-the-epidemic/opioid-crisis-statistics/index.html

